spring:
  config:
    activate:
      on-profile: local
  messages:
    cache-duration: -1
  resources:
    # キャッシュの無効化
    cache:
      period: 0
  mail:
    protocol: smtp
    host: 192.168.64.3
    port: 31025
    username: test
    password: test
    properties:
      mail:
        from: test@example.com
  r2dbc:
    url: r2dbc:pool:mysql://192.168.64.3:30306/spring-boot-r2dbc-thymeleaf-sample?useSSL=false
    username: root
    password: passw0rd
  flyway:
    schemas: spring-boot-r2dbc-thymeleaf-sample
    url: jdbc:mysql://192.168.64.3:30306/?allowPublicKeyRetrieval=true&useSSL=false
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    placeholder-replacement: false
  redis:
    host: 192.168.64.3
    port: 32379
logging:
  level:
    org.springframework.r2dbc: DEBUG

####
# アプリケーションの設定
application:
  siteUrl: http://localhost:8080
  fileUploadLocation: build/sample
  cors:
    allowedHeaders: "Origin,X-Requested-With,Content-Type,Accept,X-XSRF-TOKEN"
    allowedMethods: "POST,GET,PUT,OPTIONS,DELETE"
    allowedOrigins: "*"
